name: Lint and Test

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          {% raw -%}
          python-version: ${{ matrix.python-version }}
          {%- endraw %}
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[test]

      - name: Lint with Black
        run: black tests src --check --verbose

      - name: Run unit tests with Pytest
        run: pytest --verbose --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          {% raw -%}
          token: ${{secrets.CODECOV_TOKEN}}
          name: ${{matrix.python-version}}
          {%- endraw %}
          file: ./coverage.xml
        continue-on-error: true # I don't care THAT much about codecov
